version: '3.8'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - LOGDASH_API_KEY=${LOGDASH_API_KEY:-your-api-key}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3